name : Reusable Workflow
on: 
    workflow_call:
        inputs:
            artifact-name:
                required: true
                type: string
        outputs:
            deploy-status:
                description: 'Status of deployment'
                value:
jobs:
    deploy:
        outputs:
            outcome: ${steps.deploy-to-prod.outputs.step-result}
        name: Deploy to production
        runs-on: ubuntu-latest
        steps:
            - name: Display message
              run: echo "Deploying to production environment"
            - name: Download artifacts
              uses: actions/download-artifact@v5
              with:
                 name: ${{ inputs.artifact-name }}
            - name: List contents
              run: ls -la
            - name: Simulate deployment
              id: deploy-to-prod
              run: echo "step-result=success" >> $GITHUB_OUTPUT